name: thadam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.10
  cupertino_icons: ^1.0.8

  # Firebase & Firestore
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  http: ^1.2.0

  # PDF, Storage, and Sharing
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.0.15
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2
  share_plus: ^12.0.1
  # UI Components
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
