name: thadam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  # Firebase & Firestore
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.10


  # PDF, Storage, and Sharing
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  share_plus: ^10.0.2
  # UI Components
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  fl_chart: ^0.65.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
